<section class="events-sec"> 
  

  <div class="container">
    <h2>Booking Now <span></span></h2>
    
    <div class="booking-grey-sec">     
     <div class="col-sm-10 col-sm-10 col-sm-offset-1 col-md-offset-1 booking-grey-mid-area">
        <?php
         if(isset($this->message))
         {
             ?>
            <div class="alert-success col-md-12" style="margin-bottom: 20px; padding: 10px;">
                <?php echo $this->message; ?>
            </div>
             <?php
         }
         else
         {
            echo $this->form;
         }
         ?>
     </div>
                 
    </div>
       
      </div>
</section>



			

