<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en">
<head>
	<?php echo $this->headMeta(); ?>
	<?php echo $this->headTitle(); ?>
	<?php echo $this->headStyle(); ?>
	<?php echo $this->headLink(); ?>
	<script type="text/javascript" src="<?php echo $this->baseUrl().'/js/jquery.min.js' ;?>"></script>
	<?php echo $this->headScript(); ?>
			<script type="text/javascript">
			$(document).ready(function() {
			    // Search input text handling on focus
					var $searchq = $("#search-q").attr("value");
				    $('#search-q.text').css('color', '#999');
					$('#search-q').focus(function(){
						if ( $(this).attr('value') == $searchq) {
							$(this).css('color', '#555');
							$(this).attr('value', '');
						}
					});
					$('#search-q').blur(function(){
						if ( $(this).attr('value') == '' ) {
							$(this).attr('value', $searchq);
							$(this).css('color', '#999');
						}
					});
				// Switch categories
					$('#h-wrap').hover(function(){
							$(this).toggleClass('active');
							$("#h-wrap ul").css('display', 'block');
						}, function(){
							$(this).toggleClass('active');
							$("#h-wrap ul").css('display', 'none');
					});
				// Handling with tables (adding first and last classes for borders and adding alternate bgs)
					$('tbody tr:even').addClass('even');
					$('table.grid tbody tr:last-child').addClass('last');
					$('tr th:first-child, tr td:first-child').addClass('first');
					$('tr th:last-child, tr td:last-child').addClass('last');
					$('form.fields fieldset:last-child').addClass('last');
				// Handling with lists (alternate bgs)
					$('ul.simple li:even').addClass('even');
				// Handling with grid views (adding first and last classes for borders and adding alternate bgs)
					$('.grid .line:even').addClass('even');
					$('.grid .line:first-child').addClass('firstline');
					$('.grid .line:last-child').addClass('lastline');
				// Tabs switching
					$('#box1 .content#box1-grid').hide(); // hide content related to inactive tab by default
					$('#box1 .header ul a').click(function(){
						$('#box1 .header ul a').removeClass('active');
						$(this).addClass('active'); // make clicked tab active
						$('#box1 .content').hide(); // hide all content
						$('#box1').find('#' + $(this).attr('rel')).show(); // and show content related to clicked tab
						return false;
					});
			});
		</script>
</head>
<body>
    
	<div id="header">
		<?php echo $this->placeholder("header"); ?>
	</div>
	<div id="nav">
		<?php echo $this->placeholder("navigation"); ?>
	</div>
	<div id="container">
		<?php echo $this -> layout () -> content; ?>
		<div id="footer">
				<p><a href="#">STC</a></p>
		</div>
	</div>
    
    <script type="text/javascript">
	$(document).ready(function(){
		
		
		$('.doubleclick td.txt').dblclick(function(){
			
			row_id = $(this).parent().attr('row_id');
			
			if($(this).find('.txt_edited').length > 0) 
			{
				$('.txt_edited[row_id="'+row_id+'"]').focus();
				return;
			}
			
			old_val = $.trim($(this).html());
			
			$(this).attr('o_val', old_val);
			$(this).html('<input type="text" row_id="'+row_id+'" value="'+old_val+'" class="txt_edited" />');
			
			$('.txt_edited[row_id="'+row_id+'"]').focus();
			
			//document.location = xurl;
		});
		
		
		$('.doubleclick td.sel').dblclick(function(){
			
			row_id = $(this).parent().attr('row_id');
			
			$(this).find('select').show();
			$(this).find('span').hide();
			$(this).find('select').focus();
			
		});
		
		$('.doubleclick td.sel').live('blur', function(){
		
			$(this).find('select').hide();
			$(this).find('span').show();
			
		});
		
		$('.doubleclick td.sel select').change(function(){
		
			row_id = $(this).parent().parent().attr('row_id');
			val = $.trim($(this).val());
			txt = $.trim($(this).find('option:selected').text());
			txt_f = $(this);
			
			
			$.ajax({
					  type: "POST",
					  url: '<?php echo $this->url(array('controller' => 'camaroaccessoriesmasterlist', 'action' => 'updatecat' )); ?>',
					  data: { cat_id: val, acc_id: row_id }
					})
					  .done(function( msg ) {
						 $(txt_f).parent().find('span').html(txt);
						  
						  $(txt_f).parent().find('select').hide();
						  $(txt_f).parent().find('span').show();
						  
					  });
			
		});
		
		$('.txt_edited').live('blur', function(){
		
			$(this).parent().html($(this).parent().attr('o_val'));
			
		});
		
		$('.txt_edited').live('keyup', function(e){			
			
			if(e.keyCode == 13)
			{
				val = $.trim($(this).val());
				row_id = $(this).attr('row_id');
				
				txt_f = $(this);
				
				$.ajax({
					  type: "POST",
					  url: '<?php echo $this->url(array('controller' => 'camaroaccessoriesmasterlist', 'action' => 'updatetitle' )); ?>',
					  data: { title: val, acc_id: row_id }
					})
					  .done(function( msg ) {
						  //alert(val);
						  $(txt_f).parent().attr('o_val', val);
						 $(txt_f).parent().html($(txt_f).parent().attr('o_val'));
					  });
				
			}
			
		});
		
		
		$('.myfield_select').each(function(k, v){
			
			p = $(this).parent();
			idx = $(this).attr('next_field')+'_text';
			p.append($('label[for="'+idx+'"]').html());
			p.append($('#'+idx));
			
			$('#'+idx+'-element').remove();
			$('#'+idx+'-label').remove();
			
		});
		
		
		
		
		
		$('.myfield_text').keyup(function(e){
			
			if($.trim($(this).val()) != '')
			{
				$(this).parent().find('.myfield_select').val(0);
			}
			
		});


		$('.myfield_select').change(function(e){
			
			if($.trim($(this).val()) != '')
			{
				$(this).parent().find('.myfield_text').val("");
			}
			
		});
		
		$('#composite_form').submit(function(){
			
			vx = true;
			
			$('.myfield_select').each(function(k, v){
					$(this).parent().find('.errors').remove();
					if(vx)
					{
						txt = $(this).parent().find('.myfield_text').val();
						
						if(!$(this).parent().find('.myfield_text').hasClass('not_required'))
						{
						
								if($.trim(txt) == '' && $.trim($(this).val()) == '')
								{
									vx = false;
									
									$(this).focus();
									
									$(this).parent().append('<ul class="errors"><li>Value Required</li></ul>');
								}
								else
								{
									if($(this).parent().find('.myfield_text').hasClass('is_number'))
									{
										if(isNaN(txt))
										{
											vx = false;
									
											$(this).focus();
											
											$(this).parent().append('<ul class="errors"><li>Number Required</li></ul>');
										}
									}
								}
						}
					}
			});
			
			//alert(v);
			
			return vx;
		});
		
		
		
	});
	</script>
    
    
    
</body>
</html>
