<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<?php echo $this->headTitle(); ?>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>

<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="<?php echo $this->baseUrl(); ?>/js/bootstrap.min.js"></script>

<!-- Bootstrap -->
<link href="<?php echo $this->baseUrl(); ?>/css/bootstrap.min.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl(); ?>/css/style.css" rel="stylesheet">
<link href="<?php echo $this->baseUrl(); ?>/css/responsive.css" rel="stylesheet">
<link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css" rel="stylesheet">
<link rel="shortcut icon" href="<?php echo $this->baseUrl(); ?>/images/favicon.ico" />

<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
      <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>
    
<body id="home">

<?php echo $this->placeholder("stcheader"); ?>
<?php echo $this->placeholder("stcheaderhome"); ?>
    
<?php echo $this->layout()->content; ?>

<?php echo $this->placeholder("stcfooter"); ?>

 
<script>
$(document).ready(function(){
  // Add scrollspy to <body>
  $('body').scrollspy({target: ".navbar", offset: 80});   

  // Add smooth scrolling on all links inside the navbar
  $("#myNavbar a").on('click', function(event) {
    // Make sure this.hash has a value before overriding default behavior
    if (this.hash !== "") {
      // Prevent default anchor click behavior
      event.preventDefault();

      // Store hash
      var hash = this.hash;

      // Using jQuery's animate() method to add smooth page scroll
      // The optional number (800) specifies the number of milliseconds it takes to scroll to the specified area
     $('html, body').animate({
        scrollTop: $(hash).offset().top-104
      }, 800, function(){
   
        // Add hash (#) to URL when done scrolling (default click behavior)
      //  window.location.hash = hash;
      });
    }  // End if
  });
});
</script>
</body>

</html>



