<div class="pagination" style="width:100%">
    <ul>
    	<li>
	        <!-- First page link -->
	        <?php if (isset($this->previous)): ?>
	              <a href="<?= $this->url(array('page' => $this->first)); ?>">Start</a>
	        <?php else: ?>
	              <span class="disabled">Start</span>
	        <?php endif; ?>
        </li>
    
    	<li>
	        <!-- Previous page link -->
	        <?php if (isset($this->previous)): ?>
	              <a href="<?= $this->url(array('page' => $this->previous)); ?>">&lt; Previous</a>
	        <?php else: ?>
	            <span class="disabled">&lt; Previous</span>
	        <?php endif; ?>
        </li>
        
        
        <!-- Numbered page links -->
        <?php foreach ($this->pagesInRange as $page): ?>
            <?php if ($page != $this->current): ?>
                <li><a href="<?= $this->url(array('page' => $page)); ?>"><?= $page; ?></a></li>
            <?php else: ?>
                <li><strong><?= $page; ?></strong></li>
            <?php endif; ?>
        <?php endforeach; ?>
        
        <li>
	        <!-- Next page link -->
	        <?php if (isset($this->next)): ?>
	              <a href="<?= $this->url(array('page' => $this->next)); ?>">Next &gt;</a>
	        <?php else: ?>
	              <span class="disabled">Next &gt;</span>
	        <?php endif; ?>
        </li>
        
        <li>
	        <!-- Last page link -->
	        <?php if (isset($this->next)): ?>
	              <a href="<?= $this->url(array('page' => $this->last)); ?>">End</a>
	        <?php else: ?>
	            <span class="disabled">End</span>
	        <?php endif; ?>
	        &nbsp; Page <?= $this->current; ?> of <?= $this->last; ?>
        </li>
    </ul>
 </div>