
<!-- main section start -->

<section class="events-sec"> 
  
  <!-- events section start -->
  <div class="container">
    <h2><?php echo $this->content->title; ?><span></span></h2>
    
    <div class="booking-grey-sec">     
     <div class="col-sm-10 col-sm-10 col-sm-offset-1 col-md-offset-1 booking-grey-mid-area">
     
     <?php echo $this->content->description; ?>
     
     </div>
                 
    </div>
       
      </div>
      
      
  <!-- events section end --> 
  
 
  
</section>
<!-- main section end --> 