<div class="inner-container">
    <div class="box box-100 altbox">
        <div class="boxin">
            <div class="content">
                <div class="plain" style="padding: 30px;">
                    <h3 style="font-size: 2em;">You are not authorized to view this page</h3>
                    <br />
                    <a href="<?php echo $this->url(array('controller' => 'login', 'action' => 'index')); ?>">Login</a>
                </div>
            </div>
        </div>
    </div>
</div>