
<!-- banner section start -->

<div id="myCarousel" class="carousel slide">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <?php
        foreach($this->banner as $k => $v)
        {
            ?>
            <li index_num="<?php echo $k; ?>" class="a_click item<?php echo $v->id; ?> <?php echo ($k == 0)?'active':''; ?>"></li>
            <?php
        }
        ?>          
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
      <?php
        foreach($this->banner as $k => $v)
        {
        ?>
      <div class="item <?php echo ($k == 0)?'active':''; ?>"> 
          <?php 
          if(trim($v->banner_image_file) == '')
          {
              $v->banner_image_file = $this->baseUrl().'/images/no-image.png';
          }
          else
          {
              $v->banner_image_file = $this->baseUrl().'/public/uploads/stcartist/'.$v->banner_image_file;
          }
          ?>
        <img src="<?php echo $v->banner_image_file; ?>" class="banner-img" alt="<?php echo $v->title; ?>">
        <div class="carousel-caption">
          <div class="banner-txt"><?php echo $v->title; ?></div>
          <p><?php echo $v->description; ?></p>
        </div>
      </div>
        <?php
        }
        ?>

      
    </div>

  </div>
    
      
      
  

<!-- banner section end --> 
<script>
$(document).ready(function(){
    // Activate Carousel
    $("#myCarousel").carousel();   
    
    
    $('.a_click').click(function(){
        n = $(this).attr('index_num');
        n = Number(n);
        $("#myCarousel").carousel(n);
    });
   
});
</script>

<!-- banner section end --> 
<section class="events-sec"> 
  
  <!-- events section start -->
  <div class="container">
    <h2>Artists <span></span></h2>
    <?php
    foreach($this->artist as $k => $v)
    { 
    ?>
    <div class="artists-grey-sec">
      <div class="row col-sm-4 col-md-4 text-center mslick">
          <?php 
         $imgs = array();
          if(trim($v->image_file) == '')
          {
              $v->image_file = $this->baseUrl().'/images/no-image.png';
          }
          else
          {
              $v->image_file = $this->baseUrl().'/public/uploads/stcartist/'.$v->image_file;
          }
          $imgs[] = $v->image_file;
          
          if(trim($v->image_file_2) != '')
          {
              $imgs[] = $this->baseUrl().'/public/uploads/stcartist/'.$v->image_file_2;
          }
          if(trim($v->image_file_3) != '')
          {
              $imgs[] = $this->baseUrl().'/public/uploads/stcartist/'.$v->image_file_3;
          }
          ?>
          
          <?php
            foreach($imgs as $ki => $vi)
            {
                ?>
                <div>
                   <img style="height:200px; display: inline; xwidth: 100%;" src="<?php echo $vi; ?>"  class="img-responsive" alt="<?php echo $v->title; ?>">
               </div>
                <?php
            }
            ?>
      </div>
      <div class="col-sm-8 col-md-8">
        <div class="col-sm-8 col-md-8">
          <h3>
              <a href="<?php echo $this->baseUrl() . '/artist/single/id/'.$v->id; ?>"><?php echo $v->title; ?> </a>
          </h3>
          <p>
              <?php echo $v->description; ?>
          </p>
        </div>
        <div class="col-sm-4 col-md-4">
          <div class="btm-sec-booking" style="padding-top: 50px;"> 
              <a href="<?php echo $this->baseUrl() . '/booking/index/id/'.$v->id; ?>" class="button grey">BOOK NOW</a> 
              <br/>
              <a href="<?php echo $this->baseUrl() . '/artist/single/id/'.$v->id; ?>" class="button grey">MORE</a>
          </div>
        </div>
      </div>
    </div>
     <?php
    }
    ?>
    
    
    
      
      </div>
      
      
  <!-- events section end --> 
  
 
  
</section>



<!-- main section start -->

<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/js/slick/slick.css"/>
<script src="<?php echo $this->baseUrl();?>/js/slick/slick.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.mslick').slick({
            autoplay: true,
            autoplaySpeed: <?php echo $this->IMAGE_CHANGE_TIMEOUT*1000; ?>,
            arrows: false,
            fade: true,
            infinite: true,
            adaptiveHeight: true
        });
    });
</script>