
<!-- main section start -->

<section class="events-sec"> 
  
  <!-- events section start -->
  <div class="container">
    <h2><?php echo $this->artist->title; ?><span></span></h2>
    
    <div class="booking-grey-sec">     
     <div class="col-sm-10 col-sm-10 col-sm-offset-1 col-md-offset-1 booking-grey-mid-area">
         <?php 
         $imgs = array();
          if(trim($this->artist->image_file) == '')
          {
              $this->artist->image_file = $this->baseUrl().'/images/no-image.png';
          }
          else
          {
              $this->artist->image_file = $this->baseUrl().'/public/uploads/stcartist/'.$this->artist->image_file;
          }
          $imgs[] = $this->artist->image_file;
          
          if(trim($this->artist->image_file_2) != '')
          {
              $imgs[] = $this->baseUrl().'/public/uploads/stcartist/'.$this->artist->image_file_2;
          }
          if(trim($this->artist->image_file_3) != '')
          {
              $imgs[] = $this->baseUrl().'/public/uploads/stcartist/'.$this->artist->image_file_3;
          }
          ?>
         <div class="col-md-12 text-center mslick" style="margin-bottom: 20px;">             
            <?php
             foreach($imgs as $k => $v)
             {
                 ?>
                 <div>
                    <a class="m_image" href="<?php echo $v; ?>">
                       <img style="width: 300px; display: inline;"  src="<?php echo $v; ?>" />
                    </a>
                </div>
                 <?php
             }
             ?>
         </div>
         
         <?php echo $this->artist->long_description; ?>
         
         <div class="col-sm-4 col-md-4 text-right" style="padding: 0px;">
          <a href="<?php echo $this->baseUrl() . '/booking/index/id/'.$this->artist->id; ?>" class="button grey">BOOK NOW</a>
        </div>
     </div>
        
        
                 
    </div>
       
      </div>
      
      
  <!-- events section end --> 
  
 
  
</section>
<!-- main section end --> 

<script type="text/javascript">
    $(document).ready(function() {
	$(".m_image").fancybox();	
    });
</script>


<link href="<?php echo $this->baseUrl();?>/js/fancy/source/jquery.fancybox.css?v=2.1.5" media="screen" rel="stylesheet" type="text/css" />	
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/fancy/source/jquery.fancybox.js?v=2.1.5"></script>


<link rel="stylesheet" type="text/css" href="<?php echo $this->baseUrl();?>/js/slick/slick.css"/>
<script src="<?php echo $this->baseUrl();?>/js/slick/slick.min.js" type="text/javascript"></script>
<script type="text/javascript">
    $(document).ready(function () {
        $('.mslick').slick({
            autoplay: true,
            autoplaySpeed: <?php echo $this->IMAGE_CHANGE_TIMEOUT*1000; ?>,
            arrows: false,
            fade: true,
            infinite: true
        });
    });
</script>

