<?php $urlx = $this->baseUrl() . '/Admin/stcbooking/list'; ?>
<div class="inner-container">
    <div class="box box-100 altbox">
        <div class="boxin">
            <div class="header">
                <h3>List STC Booking</h3>
                <a class="button" href="<?php echo $this->url(array('controller' => 'stcbooking', 'action' => 'add')); ?>">
                    Add New&nbsp;&raquo;
                </a>
                <a class="button" href="<?php echo 'http://'.$_SERVER['HTTP_HOST'].$this->baseUrl()."/Admin/index"; ?>">
                    &laquo;&nbsp;Back
                </a>
                <ul>
                    <li><a rel="box1-tabular" href="#" class="active">list view</a></li>
                </ul>
            </div>
            <div class="content">
                <div class="plain">
                    <table cellspacing="0">
                        <thead>
                            <tr>
                                <th>Artist</th>
                                <th>Name</th>
                                <th>Email</th>
                                <th>Date</th>
                                <th>Actions</th>
                                
                                
                                

                            </tr>
                        </thead>
                        <?php
                        $count = 0;
						//p($this->paginator);exit();
                        foreach ($this->paginator as $p) {
														
                        ?>
                            <tr class="first <?php echo (($count++) % 2 == 0) ? 'even' : ''; ?>">
                                <td>
                                    <?php echo $this->escape($this->artist[$p->artist]); ?>
                                </td>
                                <td>
                                    <?php echo $this->escape($p->name); ?>
                                </td>
                                <td>
                                    <?php echo $this->escape($p->email); ?>
                                </td>
                               <td>
                                    <?php echo $this->escape($p->c_date); ?>
                                </td>
                                

                            <td>
                                    <a class="ico" href="<?php echo $this->url(array('controller' => 'stcbooking', 'action' => 'edit', 'id' => $p->id )); ?>">
                                    <img alt="edit" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/pencil.png" />
                                    </a>
                                        &nbsp;&nbsp;
                                    <a class="ico" href="<?php echo $this->url(array('controller' => 'stcbooking', 'action' => 'delete', 'id' => $p->id )); ?>">
                                    <img alt="delete" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/delete.png" />
                                    </a>


                            </td>
    
                        </tr>
<?php
                            }
?>
                    </table>
                </div>
<?php echo $this->paginator; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
	$(".m_image").fancybox();	
    });
</script>