
<div class="inner-container">


	<div class="box box-50 altbox">


		<div class="boxin">


			<div class="header">


				<h3>Edit event</h3>


			</div>


			<?php echo $this->form; ?>


		</div>


	</div>
</div>
<script type="text/javascript">
	$(function() {
		$( "#c_date" ).datepicker({ dateFormat: "yy-mm-dd" });	
                
	});
</script>
<style type="text/css">
    form.basic textarea{
        height: 60px;
        width: 300px;
    }
</style>