<?php $urlx = $this->baseUrl() . '/Admin/stcevent/list'; ?>
<div class="inner-container">
    <div class="box box-100 altbox">
        <div class="boxin">
            <div class="header">
                <h3>List Event</h3>
                <a class="button" href="<?php echo $this->url(array('controller' => 'stcevent', 'action' => 'add')); ?>">
                    Add New&nbsp;&raquo;
                </a>
                <a class="button" href="<?php echo 'http://'.$_SERVER['HTTP_HOST'].$this->baseUrl()."/Admin/index"; ?>">
                    &laquo;&nbsp;Back
                </a>
                <ul>
                    <li><a rel="box1-tabular" href="#" class="active">list view</a></li>
                </ul>
            </div>
            <div class="content">
                <div class="plain">
                    <table cellspacing="0">
                        <thead>
                            <tr>
                                <th>Title</th>
                                <th>Home Page Image</th>
                                <th>Event Page Image</th>
                                <th>Slider Image</th>
                                <th>is Previous?</th>
                                <th>in Homepage?</th>
                                <th>in Slider?</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <?php
                        $count = 0;
						//p($this->paginator);exit();
                        foreach ($this->paginator as $p) {
														
                        ?>
                            <tr class="first <?php echo (($count++) % 2 == 0) ? 'even' : ''; ?>">
                                <td>
<?php echo $this->escape($p->title); ?>
                                </td>
                     
       
              
                                <td>
                                    <?php
                                    if(trim($p->homepage_image) == '')
                                    {
                                        $p->homepage_image = $this->baseUrl().'/images/no-image.png';
                                    }
                                    else {
                                        $p->homepage_image = $this->baseUrl().'/public/uploads/stcevent/'.$this->escape($p->homepage_image);
                                    }
                                    ?>
                                    <a class="m_image" href="<?php echo $this->escape($p->homepage_image); ?>">
                                    <img height="100" src="<?php echo $this->escape($p->homepage_image); ?>" />                                    
                                    </a>
                                </td>
                                
                                <td>
                                    <?php
                                    if(trim($p->event_page_image) == '')
                                    {
                                        $p->event_page_image = $this->baseUrl().'/images/no-image.png';
                                    }
                                    else {
                                        $p->event_page_image = $this->baseUrl().'/public/uploads/stcevent/'.$this->escape($p->event_page_image);
                                    }
                                    ?>
                                    <a class="m_image" href="<?php echo $this->escape($p->event_page_image); ?>">
                                    <img height="100" src="<?php echo $this->escape($p->event_page_image); ?>" />                                    
                                    </a>
                                </td>
                                
                                <td>
                                    <?php
                                    if(trim($p->slider_image) == '')
                                    {
                                        $p->slider_image = $this->baseUrl().'/images/no-image.png';
                                    }
                                    else {
                                        $p->slider_image = $this->baseUrl().'/public/uploads/stcevent/'.$this->escape($p->slider_image);
                                    }
                                    ?>
                                    <a class="m_image" href="<?php echo $this->escape($p->slider_image); ?>">
                                        <img height="100" src="<?php echo $this->escape($p->slider_image); ?>" />                                    
                                    </a>
                                </td>
                      <td>
             <?php 
            if($this->escape($p->is_previous) == '1')
            {
              ?>
                 <a href="<?php echo $urlx.'/unpublish/'.$p->id;?>">
                    <img alt="unpublish" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/publish_g.png" />
                </a>
                <?php
            }
            else
            {
                ?>
                 <a href="<?php echo $urlx.'/publish/'.$p->id; ?>">
                    <img alt="publish" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/publish_x.png" />
                </a>
                <?php
            }
            ?>
                                </td>
                                 <td>
                                        <?php 
                                if($this->escape($p->publish_to_homepage) == '1')
                                {
                                    ?>
                                     <a href="<?php echo $urlx.'/unpublishbanner/'.$p->id;?>">
                                        <img alt="unpublish" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/publish_g.png" />
                                    </a>
                                    <?php
                                }
                                else
                                {
                                    ?>
                                     <a href="<?php echo $urlx.'/publishbanner/'.$p->id; ?>">
                                        <img alt="publish" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/publish_x.png" />
                                    </a>
                                    <?php
                                }
                                ?>
                                </td>
                                
                            <td>
                <?php 
        if($this->escape($p->show_in_slider) == '1')
        {
            ?>
             <a href="<?php echo $urlx.'/unpublishslider/'.$p->id;?>">
                <img alt="unpublish" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/publish_g.png" />
            </a>
            <?php
        }
        else
        {
            ?>
             <a href="<?php echo $urlx.'/publishslider/'.$p->id; ?>">
                <img alt="publish" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/publish_x.png" />
            </a>
            <?php
        }
        ?>
        </td>
                             
                            
                            
                            
                            <td>

<a class="ico" href="<?php echo $this->url(array('controller' => 'stcevent', 'action' => 'edit', 'id' => $p->id )); ?>">


<img alt="edit" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/pencil.png" />


</a>


&nbsp;&nbsp;


<a class="ico" href="<?php echo $this->url(array('controller' => 'stcevent', 'action' => 'delete', 'id' => $p->id )); ?>">
<img alt="delete" src="<?php echo $this->baseUrl(); ?>/css/admin/img/led-ico/delete.png" />

</a>
</td>
                            
                          
                            
 </tr>
<?php
                            }
?>
</table>
                </div>
<?php echo $this->paginator; ?>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(document).ready(function() {
	$(".m_image").fancybox();	
    });
</script>
